// PasswordResetSession.cs
// Entity model representing a single password-reset attempt initiated by a user.
// The reset flow is a two-step process:
//   Step 1 — User requests a reset → a 6-digit OTP is emailed to them.
//             A session row is created with the OTP hash and an expiry time.
//   Step 2 — User submits the OTP → if valid, a short-lived reset token is issued.
//   Step 3 — User submits the reset token + new password → password is updated
//             and the session is marked as used.
// Storing sessions in the database (rather than in-memory or cache) ensures
// they survive service restarts and can be audited.
// Mapped to the [PasswordResetSessions] table in SQL Server by EF Core.

namespace AuthService.Models;

// Marked partial to allow EF Core scaffolding to regenerate without
// overwriting any hand-written additions.
public partial class PasswordResetSession
{
    // Primary key — GUID generated by the database (DEFAULT NEWID()).
    public Guid Id { get; set; }

    // Foreign key to the [Users] table — identifies whose password is being reset.
    // Cascades on delete so orphaned sessions are cleaned up automatically.
    public Guid UserId { get; set; }

    // Describes why this session was created.
    // Currently always "PASSWORD_RESET", but the field exists so the same
    // table can be reused for other OTP-based flows (e.g. email verification)
    // without a schema change.
    public string Purpose { get; set; } = null!;

    // SHA-256 hash of the 6-digit OTP sent to the user's email.
    // We never store the raw OTP — only its hash — so a database leak
    // cannot be used to reset someone's password.
    public string OtpHash { get; set; } = null!;

    // SHA-256 hash of the short-lived reset token issued after OTP verification.
    // Null until the OTP has been successfully verified (Step 2).
    public string? ResetTokenHash { get; set; }

    // UTC time after which the OTP is no longer valid.
    // Set to 10 minutes from session creation to limit the attack window.
    public DateTime OtpExpiresAtUtc { get; set; }

    // UTC time after which the reset token is no longer valid.
    // Set to 10 minutes from OTP verification.
    // Null until the OTP has been verified.
    public DateTime? ResetTokenExpiresAtUtc { get; set; }

    // UTC timestamp of when the OTP was successfully verified.
    // Null until Step 2 completes. Used to find the "latest verified" session
    // when the user submits their new password.
    public DateTime? VerifiedAtUtc { get; set; }

    // UTC timestamp of when the reset token was consumed to change the password.
    // Once set, this session is considered "used" and cannot be reused.
    // Sessions with UsedAtUtc == null are considered "active".
    public DateTime? UsedAtUtc { get; set; }

    // Number of failed OTP verification attempts so far.
    // Incremented each time the user submits a wrong OTP.
    public int Attempts { get; set; }

    // Maximum number of OTP attempts allowed before the session is locked.
    // Defaults to 5 at the database level to prevent brute-force OTP guessing.
    public int MaxAttempts { get; set; }

    // UTC timestamp of when this session row was inserted.
    // Defaults to the current UTC time at the database level.
    // Used to order sessions and find the most recent one.
    public DateTime CreatedAtUtc { get; set; }

    // UTC timestamp of the most recent OTP attempt (successful or not).
    // Useful for rate-limiting and audit trails.
    public DateTime? LastAttemptAtUtc { get; set; }

    // Navigation property — EF Core populates this with the owning User row
    // when the query uses .Include(s => s.User).
    // Non-nullable because a session cannot exist without a user.
    public virtual User User { get; set; } = null!;
}
