SELECT 'WalletAuth' AS DB, TABLE_NAME FROM WalletAuth.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'
UNION ALL
SELECT 'WalletWallet', TABLE_NAME FROM WalletWallet.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'
UNION ALL
SELECT 'WalletPayment', TABLE_NAME FROM WalletPayment.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'
UNION ALL
SELECT 'WalletAdmin', TABLE_NAME FROM WalletAdmin.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'
UNION ALL
SELECT 'WalletReward', TABLE_NAME FROM WalletReward.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY DB, TABLE_NAME;