using System;
using System.Collections.Generic;

namespace WalletService.Models;

// Represents a single financial event on a wallet — a top-up, transfer leg,
// cashback credit, or admin adjustment. Every change to a wallet balance must
// produce a transaction record so there is a complete, auditable ledger.
// Transactions are immutable once written; they are never updated or deleted.
public partial class WalletTransaction
{
    // Primary key — uniquely identifies this transaction row.
    // Generated by SQL Server (newid()) so no application-side ID management is needed.
    public Guid Id { get; set; }

    // The wallet that "owns" this transaction entry — i.e. the wallet whose
    // balance was affected. FK to Wallets.Id with no cascade delete so that
    // deleting a wallet (if ever supported) does not silently wipe audit history.
    public Guid WalletId { get; set; }

    // For peer-to-peer transfers, this holds the other party's wallet ID.
    // Null for top-ups, cashbacks, and admin adjustments that have no counterpart.
    // Allows the UI to display "sent to / received from" information.
    public Guid? ToWalletId { get; set; }

    // Describes the nature of the transaction. Known values:
    //   "topup"            — user added funds
    //   "transfer_out"     — user sent money to another wallet
    //   "transfer_in"      — user received money from another wallet
    //   "cashback"         — campaign reward credited automatically
    //   "admin_adjustment" — balance corrected by an admin
    // Stored as a string so new types can be added without a schema migration.
    public string Type { get; set; } = null!;

    // The monetary value of this event, stored as decimal(18,2).
    // Positive for credits (topup, transfer_in, cashback).
    // Negative for debits (transfer_out) or the delta in admin_adjustment.
    public decimal Amount { get; set; }

    // The wallet's balance immediately after this transaction was applied.
    // Stored redundantly for fast statement generation — avoids replaying
    // the entire transaction history to reconstruct a running balance.
    public decimal BalanceAfter { get; set; }

    // Outcome of the transaction. Typically "Success"; could be "Failed" or
    // "Pending" if async processing is ever introduced. Stored so the UI can
    // surface failed attempts without hiding them from the audit trail.
    public string Status { get; set; } = null!;

    // Human-readable unique reference code (e.g. "TP20240101120000ABCDEF123456").
    // Used for customer support lookups and cross-service correlation.
    // A unique index on this column prevents duplicate reference codes.
    public string Reference { get; set; } = null!;

    // Optional free-text note supplied by the user or admin at the time of
    // the transaction (e.g. "Rent payment"). Null when no note was provided.
    public string? Note { get; set; }

    // UTC timestamp of when this transaction was recorded.
    // Set by the database default (getutcdate()) and never changed afterwards.
    public DateTime CreatedAt { get; set; }

    // Navigation property back to the owning Wallet entity.
    // EF Core uses this to materialise the FK relationship when Include() is called.
    public virtual Wallet Wallet { get; set; } = null!;
}
