using System;
using System.Collections.Generic;

namespace WalletService.Models;

// Represents a user's digital wallet in the system.
// Each user gets exactly one wallet (enforced by a unique index on UserId).
// The wallet holds the current balance and lock state — it is the financial
// account that all top-ups, transfers, and cashbacks operate against.
public partial class Wallet
{
    // Primary key — uniquely identifies this wallet record in the database.
    // Generated by SQL Server (newid()) so we never need to supply it manually.
    public Guid Id { get; set; }

    // Foreign key linking this wallet to a user in AuthService.
    // There is a unique index on this column so one user can never have two wallets.
    public Guid UserId { get; set; }

    // The current available balance in the wallet, stored as decimal(18,2)
    // to avoid floating-point rounding errors on monetary values.
    public decimal Balance { get; set; }

    // ISO currency code (e.g. "INR"). Defaults to "INR" at the database level.
    // Stored so that future multi-currency support requires no schema change.
    public string Currency { get; set; } = null!;

    // When true, all debit operations (transfers, withdrawals) are blocked.
    // Admins can lock a wallet for fraud investigation or compliance reasons.
    public bool IsLocked { get; set; }

    // UTC timestamp of when the wallet was first created.
    // Set once by the database default (getutcdate()) and never updated.
    public DateTime CreatedAt { get; set; }

    // UTC timestamp of the last time the wallet record was modified
    // (balance change, lock toggle, etc.). Updated on every write operation.
    public DateTime UpdatedAt { get; set; }

    // Navigation property — the full list of transactions that belong to this wallet.
    // EF Core uses this to build the FK relationship with WalletTransaction.WalletId.
    // Initialised to an empty list so callers never get a null reference.
    public virtual ICollection<WalletTransaction> WalletTransactions { get; set; } = new List<WalletTransaction>();
}
