using System;
using System.Collections.Generic;

namespace AdminService.Models;

// Represents a single KYC (Know Your Customer) review record in the AdminService database.
// When a user submits their identity documents in AuthService, a message is published
// to the "kyc_submissions" queue. The KycSubmissionConsumer picks it up and creates
// (or updates) one of these records so admins can review it through the admin panel.
// The lifecycle is: Pending → Approved | Rejected.
public partial class KycReview
{
    // Primary key — uniquely identifies this KYC review row.
    // Generated by SQL Server (newid()) so no application-side ID management is needed.
    public Guid Id { get; set; }

    // The ID of the user whose identity is being reviewed.
    // A unique index on this column ensures one user can only have one active review.
    public Guid UserId { get; set; }

    // The user's full name as provided during KYC submission.
    // Stored here so admins can see the name without calling AuthService.
    public string UserFullName { get; set; } = null!;

    // The user's email address, copied from AuthService at submission time.
    // Used to send KYC decision notifications directly without an extra lookup.
    public string UserEmail { get; set; } = null!;

    // The type of identity document submitted (e.g. "Passport", "Aadhaar", "PAN").
    // Determines what the admin should look for when verifying the document number.
    public string DocumentType { get; set; } = null!;

    // The actual document identifier (e.g. passport number, Aadhaar number).
    // Admins use this to cross-check against the submitted document image.
    public string DocumentNumber { get; set; } = null!;

    // Current review state. Possible values: "Pending", "Approved", "Rejected".
    // Defaults to "Pending" at the database level when a new record is inserted.
    public string Status { get; set; } = null!;

    // Optional note left by the admin when making a decision.
    // Required when rejecting so the user understands why and can resubmit.
    // Null when the review is still pending or was approved without a note.
    public string? AdminNote { get; set; }

    // The ID of the admin user who made the Approved/Rejected decision.
    // Null while the review is still pending. Used for accountability tracking.
    public Guid? ReviewedBy { get; set; }

    // UTC timestamp of when the user originally submitted their KYC documents.
    // Used to sort the pending queue (oldest first) so no submission is forgotten.
    public DateTime SubmittedAt { get; set; }

    // UTC timestamp of when an admin made the final decision.
    // Null while the review is still pending. Stored for audit and SLA reporting.
    public DateTime? ReviewedAt { get; set; }
}
