using System;
using System.Collections.Generic;

namespace AdminService.Models;

// Represents a support ticket raised by a user through the app.
// Users submit tickets when they have issues or questions; admins reply
// through the admin panel. The lifecycle is: Open → Responded.
// Tickets are never deleted — they form a permanent support history.
public partial class SupportTicket
{
    // Primary key — uniquely identifies this support ticket row.
    // Generated by SQL Server (newid()) so no application-side ID management is needed.
    public Guid Id { get; set; }

    // The ID of the user who submitted this ticket.
    // Used to filter "my tickets" for the user-facing endpoint and to
    // send reply notifications to the correct user.
    public Guid UserId { get; set; }

    // The user's email address at the time of submission.
    // Stored here so notification messages can be sent without calling AuthService.
    public string UserEmail { get; set; } = null!;

    // A short summary of the issue (max 300 chars).
    // Displayed in the admin ticket list so admins can triage without opening each ticket.
    public string Subject { get; set; } = null!;

    // The full description of the user's issue or question.
    // No length limit enforced at the model level — the DB column is nvarchar(max).
    public string Message { get; set; } = null!;

    // Current ticket state. Possible values: "Open", "Responded".
    // Defaults to "Open" at the database level when a new ticket is inserted.
    // Updated to "Responded" when an admin submits a reply.
    public string Status { get; set; } = null!;

    // The admin's reply text. Null until an admin responds to the ticket.
    // Sent to the user via the notification service when set.
    public string? AdminReply { get; set; }

    // The ID of the admin who replied to this ticket.
    // Null while the ticket is still open. Used for accountability tracking.
    public Guid? RespondedBy { get; set; }

    // UTC timestamp of when the user submitted the ticket.
    // Set by the database default (getutcdate()). Used to sort the admin queue.
    public DateTime CreatedAt { get; set; }

    // UTC timestamp of when an admin sent a reply.
    // Null while the ticket is still open. Stored for SLA and audit purposes.
    public DateTime? RespondedAt { get; set; }
}
